sonar.projectKey=siurbAutoClip
sonar.projectName=siurbAutoClip
sonar.sources=.
sonar.exclusions=**/venv/**,**/.venv/**,**/__pycache__/**,**/*.pyc,**/migrations/**,**/poppler-25.12.0/**
sonar.python.version=3.11
sonar.sourceEncoding=UTF-8
